controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation



home_page:
    path: /
    controller: App\Controller\FruitController::index

fruit_list:
    path: /fruits
    controller: App\Controller\FruitController::list

fruit_favorites:
    path: /fruits/favorites
    controller: App\Controller\FruitController::favorites